; Auto-generated. Do not edit!


(cl:in-package aubo_msgs-msg)


;//! \htmlinclude IOState.msg.html

(cl:defclass <IOState> (roslisp-msg-protocol:ros-message)
  ((stamp
    :reader stamp
    :initarg :stamp
    :type cl:string
    :initform "")
   (digital_in_states
    :reader digital_in_states
    :initarg :digital_in_states
    :type (cl:vector aubo_msgs-msg:Digital)
   :initform (cl:make-array 0 :element-type 'aubo_msgs-msg:Digital :initial-element (cl:make-instance 'aubo_msgs-msg:Digital)))
   (digital_out_states
    :reader digital_out_states
    :initarg :digital_out_states
    :type (cl:vector aubo_msgs-msg:Digital)
   :initform (cl:make-array 0 :element-type 'aubo_msgs-msg:Digital :initial-element (cl:make-instance 'aubo_msgs-msg:Digital)))
   (analog_in_states
    :reader analog_in_states
    :initarg :analog_in_states
    :type (cl:vector aubo_msgs-msg:Analog)
   :initform (cl:make-array 0 :element-type 'aubo_msgs-msg:Analog :initial-element (cl:make-instance 'aubo_msgs-msg:Analog)))
   (analog_out_states
    :reader analog_out_states
    :initarg :analog_out_states
    :type (cl:vector aubo_msgs-msg:Analog)
   :initform (cl:make-array 0 :element-type 'aubo_msgs-msg:Analog :initial-element (cl:make-instance 'aubo_msgs-msg:Analog)))
   (tool_io_states
    :reader tool_io_states
    :initarg :tool_io_states
    :type (cl:vector aubo_msgs-msg:Digital)
   :initform (cl:make-array 0 :element-type 'aubo_msgs-msg:Digital :initial-element (cl:make-instance 'aubo_msgs-msg:Digital)))
   (tool_ai_states
    :reader tool_ai_states
    :initarg :tool_ai_states
    :type (cl:vector aubo_msgs-msg:Analog)
   :initform (cl:make-array 0 :element-type 'aubo_msgs-msg:Analog :initial-element (cl:make-instance 'aubo_msgs-msg:Analog)))
   (safety_in_states
    :reader safety_in_states
    :initarg :safety_in_states
    :type (cl:vector aubo_msgs-msg:Digital)
   :initform (cl:make-array 0 :element-type 'aubo_msgs-msg:Digital :initial-element (cl:make-instance 'aubo_msgs-msg:Digital)))
   (safety_out_states
    :reader safety_out_states
    :initarg :safety_out_states
    :type (cl:vector aubo_msgs-msg:Digital)
   :initform (cl:make-array 0 :element-type 'aubo_msgs-msg:Digital :initial-element (cl:make-instance 'aubo_msgs-msg:Digital))))
)

(cl:defclass IOState (<IOState>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <IOState>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'IOState)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aubo_msgs-msg:<IOState> is deprecated: use aubo_msgs-msg:IOState instead.")))

(cl:ensure-generic-function 'stamp-val :lambda-list '(m))
(cl:defmethod stamp-val ((m <IOState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aubo_msgs-msg:stamp-val is deprecated.  Use aubo_msgs-msg:stamp instead.")
  (stamp m))

(cl:ensure-generic-function 'digital_in_states-val :lambda-list '(m))
(cl:defmethod digital_in_states-val ((m <IOState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aubo_msgs-msg:digital_in_states-val is deprecated.  Use aubo_msgs-msg:digital_in_states instead.")
  (digital_in_states m))

(cl:ensure-generic-function 'digital_out_states-val :lambda-list '(m))
(cl:defmethod digital_out_states-val ((m <IOState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aubo_msgs-msg:digital_out_states-val is deprecated.  Use aubo_msgs-msg:digital_out_states instead.")
  (digital_out_states m))

(cl:ensure-generic-function 'analog_in_states-val :lambda-list '(m))
(cl:defmethod analog_in_states-val ((m <IOState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aubo_msgs-msg:analog_in_states-val is deprecated.  Use aubo_msgs-msg:analog_in_states instead.")
  (analog_in_states m))

(cl:ensure-generic-function 'analog_out_states-val :lambda-list '(m))
(cl:defmethod analog_out_states-val ((m <IOState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aubo_msgs-msg:analog_out_states-val is deprecated.  Use aubo_msgs-msg:analog_out_states instead.")
  (analog_out_states m))

(cl:ensure-generic-function 'tool_io_states-val :lambda-list '(m))
(cl:defmethod tool_io_states-val ((m <IOState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aubo_msgs-msg:tool_io_states-val is deprecated.  Use aubo_msgs-msg:tool_io_states instead.")
  (tool_io_states m))

(cl:ensure-generic-function 'tool_ai_states-val :lambda-list '(m))
(cl:defmethod tool_ai_states-val ((m <IOState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aubo_msgs-msg:tool_ai_states-val is deprecated.  Use aubo_msgs-msg:tool_ai_states instead.")
  (tool_ai_states m))

(cl:ensure-generic-function 'safety_in_states-val :lambda-list '(m))
(cl:defmethod safety_in_states-val ((m <IOState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aubo_msgs-msg:safety_in_states-val is deprecated.  Use aubo_msgs-msg:safety_in_states instead.")
  (safety_in_states m))

(cl:ensure-generic-function 'safety_out_states-val :lambda-list '(m))
(cl:defmethod safety_out_states-val ((m <IOState>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aubo_msgs-msg:safety_out_states-val is deprecated.  Use aubo_msgs-msg:safety_out_states instead.")
  (safety_out_states m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <IOState>) ostream)
  "Serializes a message object of type '<IOState>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'stamp))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'stamp))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'digital_in_states))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'digital_in_states))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'digital_out_states))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'digital_out_states))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'analog_in_states))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'analog_in_states))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'analog_out_states))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'analog_out_states))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'tool_io_states))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'tool_io_states))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'tool_ai_states))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'tool_ai_states))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'safety_in_states))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'safety_in_states))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'safety_out_states))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'safety_out_states))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <IOState>) istream)
  "Deserializes a message object of type '<IOState>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'stamp) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'stamp) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'digital_in_states) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'digital_in_states)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'aubo_msgs-msg:Digital))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'digital_out_states) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'digital_out_states)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'aubo_msgs-msg:Digital))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'analog_in_states) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'analog_in_states)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'aubo_msgs-msg:Analog))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'analog_out_states) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'analog_out_states)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'aubo_msgs-msg:Analog))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'tool_io_states) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'tool_io_states)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'aubo_msgs-msg:Digital))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'tool_ai_states) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'tool_ai_states)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'aubo_msgs-msg:Analog))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'safety_in_states) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'safety_in_states)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'aubo_msgs-msg:Digital))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'safety_out_states) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'safety_out_states)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'aubo_msgs-msg:Digital))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<IOState>)))
  "Returns string type for a message object of type '<IOState>"
  "aubo_msgs/IOState")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'IOState)))
  "Returns string type for a message object of type 'IOState"
  "aubo_msgs/IOState")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<IOState>)))
  "Returns md5sum for a message object of type '<IOState>"
  "9ec6dbb17bd90dfffb00b6e735866ab5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'IOState)))
  "Returns md5sum for a message object of type 'IOState"
  "9ec6dbb17bd90dfffb00b6e735866ab5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<IOState>)))
  "Returns full string definition for message of type '<IOState>"
  (cl:format cl:nil "string stamp ~%Digital[] digital_in_states~%Digital[] digital_out_states~%Analog[] analog_in_states~%Analog[] analog_out_states~%Digital[] tool_io_states~%Analog[] tool_ai_states~%Digital[] safety_in_states~%Digital[] safety_out_states~%~%================================================================================~%MSG: aubo_msgs/Digital~%uint8 pin~%bool flag~%bool state~%~%================================================================================~%MSG: aubo_msgs/Analog~%uint8 pin~%float32 state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'IOState)))
  "Returns full string definition for message of type 'IOState"
  (cl:format cl:nil "string stamp ~%Digital[] digital_in_states~%Digital[] digital_out_states~%Analog[] analog_in_states~%Analog[] analog_out_states~%Digital[] tool_io_states~%Analog[] tool_ai_states~%Digital[] safety_in_states~%Digital[] safety_out_states~%~%================================================================================~%MSG: aubo_msgs/Digital~%uint8 pin~%bool flag~%bool state~%~%================================================================================~%MSG: aubo_msgs/Analog~%uint8 pin~%float32 state~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <IOState>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'stamp))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'digital_in_states) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'digital_out_states) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'analog_in_states) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'analog_out_states) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'tool_io_states) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'tool_ai_states) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'safety_in_states) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'safety_out_states) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <IOState>))
  "Converts a ROS message object to a list"
  (cl:list 'IOState
    (cl:cons ':stamp (stamp msg))
    (cl:cons ':digital_in_states (digital_in_states msg))
    (cl:cons ':digital_out_states (digital_out_states msg))
    (cl:cons ':analog_in_states (analog_in_states msg))
    (cl:cons ':analog_out_states (analog_out_states msg))
    (cl:cons ':tool_io_states (tool_io_states msg))
    (cl:cons ':tool_ai_states (tool_ai_states msg))
    (cl:cons ':safety_in_states (safety_in_states msg))
    (cl:cons ':safety_out_states (safety_out_states msg))
))
