// Generated by gencpp from file aubo_msgs/GetFK.msg
// DO NOT EDIT!


#ifndef AUBO_MSGS_MESSAGE_GETFK_H
#define AUBO_MSGS_MESSAGE_GETFK_H

#include <ros/service_traits.h>


#include <aubo_msgs/GetFKRequest.h>
#include <aubo_msgs/GetFKResponse.h>


namespace aubo_msgs
{

struct GetFK
{

typedef GetFKRequest Request;
typedef GetFKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFK
} // namespace aubo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aubo_msgs::GetFK > {
  static const char* value()
  {
    return "ce6ffdfba920b489febbc60ddc59a871";
  }

  static const char* value(const ::aubo_msgs::GetFK&) { return value(); }
};

template<>
struct DataType< ::aubo_msgs::GetFK > {
  static const char* value()
  {
    return "aubo_msgs/GetFK";
  }

  static const char* value(const ::aubo_msgs::GetFK&) { return value(); }
};


// service_traits::MD5Sum< ::aubo_msgs::GetFKRequest> should match
// service_traits::MD5Sum< ::aubo_msgs::GetFK >
template<>
struct MD5Sum< ::aubo_msgs::GetFKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aubo_msgs::GetFK >::value();
  }
  static const char* value(const ::aubo_msgs::GetFKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aubo_msgs::GetFKRequest> should match
// service_traits::DataType< ::aubo_msgs::GetFK >
template<>
struct DataType< ::aubo_msgs::GetFKRequest>
{
  static const char* value()
  {
    return DataType< ::aubo_msgs::GetFK >::value();
  }
  static const char* value(const ::aubo_msgs::GetFKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aubo_msgs::GetFKResponse> should match
// service_traits::MD5Sum< ::aubo_msgs::GetFK >
template<>
struct MD5Sum< ::aubo_msgs::GetFKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aubo_msgs::GetFK >::value();
  }
  static const char* value(const ::aubo_msgs::GetFKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aubo_msgs::GetFKResponse> should match
// service_traits::DataType< ::aubo_msgs::GetFK >
template<>
struct DataType< ::aubo_msgs::GetFKResponse>
{
  static const char* value()
  {
    return DataType< ::aubo_msgs::GetFK >::value();
  }
  static const char* value(const ::aubo_msgs::GetFKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUBO_MSGS_MESSAGE_GETFK_H
