// Generated by gencpp from file aubo_msgs/IOState.msg
// DO NOT EDIT!


#ifndef AUBO_MSGS_MESSAGE_IOSTATE_H
#define AUBO_MSGS_MESSAGE_IOSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <aubo_msgs/Digital.h>
#include <aubo_msgs/Digital.h>
#include <aubo_msgs/Analog.h>
#include <aubo_msgs/Analog.h>
#include <aubo_msgs/Digital.h>
#include <aubo_msgs/Analog.h>
#include <aubo_msgs/Digital.h>
#include <aubo_msgs/Digital.h>

namespace aubo_msgs
{
template <class ContainerAllocator>
struct IOState_
{
  typedef IOState_<ContainerAllocator> Type;

  IOState_()
    : stamp()
    , digital_in_states()
    , digital_out_states()
    , analog_in_states()
    , analog_out_states()
    , tool_io_states()
    , tool_ai_states()
    , safety_in_states()
    , safety_out_states()  {
    }
  IOState_(const ContainerAllocator& _alloc)
    : stamp(_alloc)
    , digital_in_states(_alloc)
    , digital_out_states(_alloc)
    , analog_in_states(_alloc)
    , analog_out_states(_alloc)
    , tool_io_states(_alloc)
    , tool_ai_states(_alloc)
    , safety_in_states(_alloc)
    , safety_out_states(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _stamp_type;
  _stamp_type stamp;

   typedef std::vector< ::aubo_msgs::Digital_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aubo_msgs::Digital_<ContainerAllocator> >> _digital_in_states_type;
  _digital_in_states_type digital_in_states;

   typedef std::vector< ::aubo_msgs::Digital_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aubo_msgs::Digital_<ContainerAllocator> >> _digital_out_states_type;
  _digital_out_states_type digital_out_states;

   typedef std::vector< ::aubo_msgs::Analog_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aubo_msgs::Analog_<ContainerAllocator> >> _analog_in_states_type;
  _analog_in_states_type analog_in_states;

   typedef std::vector< ::aubo_msgs::Analog_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aubo_msgs::Analog_<ContainerAllocator> >> _analog_out_states_type;
  _analog_out_states_type analog_out_states;

   typedef std::vector< ::aubo_msgs::Digital_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aubo_msgs::Digital_<ContainerAllocator> >> _tool_io_states_type;
  _tool_io_states_type tool_io_states;

   typedef std::vector< ::aubo_msgs::Analog_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aubo_msgs::Analog_<ContainerAllocator> >> _tool_ai_states_type;
  _tool_ai_states_type tool_ai_states;

   typedef std::vector< ::aubo_msgs::Digital_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aubo_msgs::Digital_<ContainerAllocator> >> _safety_in_states_type;
  _safety_in_states_type safety_in_states;

   typedef std::vector< ::aubo_msgs::Digital_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::aubo_msgs::Digital_<ContainerAllocator> >> _safety_out_states_type;
  _safety_out_states_type safety_out_states;





  typedef boost::shared_ptr< ::aubo_msgs::IOState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aubo_msgs::IOState_<ContainerAllocator> const> ConstPtr;

}; // struct IOState_

typedef ::aubo_msgs::IOState_<std::allocator<void> > IOState;

typedef boost::shared_ptr< ::aubo_msgs::IOState > IOStatePtr;
typedef boost::shared_ptr< ::aubo_msgs::IOState const> IOStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aubo_msgs::IOState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aubo_msgs::IOState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aubo_msgs::IOState_<ContainerAllocator1> & lhs, const ::aubo_msgs::IOState_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.digital_in_states == rhs.digital_in_states &&
    lhs.digital_out_states == rhs.digital_out_states &&
    lhs.analog_in_states == rhs.analog_in_states &&
    lhs.analog_out_states == rhs.analog_out_states &&
    lhs.tool_io_states == rhs.tool_io_states &&
    lhs.tool_ai_states == rhs.tool_ai_states &&
    lhs.safety_in_states == rhs.safety_in_states &&
    lhs.safety_out_states == rhs.safety_out_states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aubo_msgs::IOState_<ContainerAllocator1> & lhs, const ::aubo_msgs::IOState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aubo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aubo_msgs::IOState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aubo_msgs::IOState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aubo_msgs::IOState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aubo_msgs::IOState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aubo_msgs::IOState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aubo_msgs::IOState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aubo_msgs::IOState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ec6dbb17bd90dfffb00b6e735866ab5";
  }

  static const char* value(const ::aubo_msgs::IOState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ec6dbb17bd90dffULL;
  static const uint64_t static_value2 = 0xfb00b6e735866ab5ULL;
};

template<class ContainerAllocator>
struct DataType< ::aubo_msgs::IOState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aubo_msgs/IOState";
  }

  static const char* value(const ::aubo_msgs::IOState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aubo_msgs::IOState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string stamp \n"
"Digital[] digital_in_states\n"
"Digital[] digital_out_states\n"
"Analog[] analog_in_states\n"
"Analog[] analog_out_states\n"
"Digital[] tool_io_states\n"
"Analog[] tool_ai_states\n"
"Digital[] safety_in_states\n"
"Digital[] safety_out_states\n"
"\n"
"================================================================================\n"
"MSG: aubo_msgs/Digital\n"
"uint8 pin\n"
"bool flag\n"
"bool state\n"
"\n"
"================================================================================\n"
"MSG: aubo_msgs/Analog\n"
"uint8 pin\n"
"float32 state\n"
;
  }

  static const char* value(const ::aubo_msgs::IOState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aubo_msgs::IOState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.digital_in_states);
      stream.next(m.digital_out_states);
      stream.next(m.analog_in_states);
      stream.next(m.analog_out_states);
      stream.next(m.tool_io_states);
      stream.next(m.tool_ai_states);
      stream.next(m.safety_in_states);
      stream.next(m.safety_out_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IOState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aubo_msgs::IOState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aubo_msgs::IOState_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.stamp);
    s << indent << "digital_in_states[]" << std::endl;
    for (size_t i = 0; i < v.digital_in_states.size(); ++i)
    {
      s << indent << "  digital_in_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aubo_msgs::Digital_<ContainerAllocator> >::stream(s, indent + "    ", v.digital_in_states[i]);
    }
    s << indent << "digital_out_states[]" << std::endl;
    for (size_t i = 0; i < v.digital_out_states.size(); ++i)
    {
      s << indent << "  digital_out_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aubo_msgs::Digital_<ContainerAllocator> >::stream(s, indent + "    ", v.digital_out_states[i]);
    }
    s << indent << "analog_in_states[]" << std::endl;
    for (size_t i = 0; i < v.analog_in_states.size(); ++i)
    {
      s << indent << "  analog_in_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aubo_msgs::Analog_<ContainerAllocator> >::stream(s, indent + "    ", v.analog_in_states[i]);
    }
    s << indent << "analog_out_states[]" << std::endl;
    for (size_t i = 0; i < v.analog_out_states.size(); ++i)
    {
      s << indent << "  analog_out_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aubo_msgs::Analog_<ContainerAllocator> >::stream(s, indent + "    ", v.analog_out_states[i]);
    }
    s << indent << "tool_io_states[]" << std::endl;
    for (size_t i = 0; i < v.tool_io_states.size(); ++i)
    {
      s << indent << "  tool_io_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aubo_msgs::Digital_<ContainerAllocator> >::stream(s, indent + "    ", v.tool_io_states[i]);
    }
    s << indent << "tool_ai_states[]" << std::endl;
    for (size_t i = 0; i < v.tool_ai_states.size(); ++i)
    {
      s << indent << "  tool_ai_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aubo_msgs::Analog_<ContainerAllocator> >::stream(s, indent + "    ", v.tool_ai_states[i]);
    }
    s << indent << "safety_in_states[]" << std::endl;
    for (size_t i = 0; i < v.safety_in_states.size(); ++i)
    {
      s << indent << "  safety_in_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aubo_msgs::Digital_<ContainerAllocator> >::stream(s, indent + "    ", v.safety_in_states[i]);
    }
    s << indent << "safety_out_states[]" << std::endl;
    for (size_t i = 0; i < v.safety_out_states.size(); ++i)
    {
      s << indent << "  safety_out_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aubo_msgs::Digital_<ContainerAllocator> >::stream(s, indent + "    ", v.safety_out_states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUBO_MSGS_MESSAGE_IOSTATE_H
