// Generated by gencpp from file aubo_msgs/SetIORequest.msg
// DO NOT EDIT!


#ifndef AUBO_MSGS_MESSAGE_SETIOREQUEST_H
#define AUBO_MSGS_MESSAGE_SETIOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aubo_msgs
{
template <class ContainerAllocator>
struct SetIORequest_
{
  typedef SetIORequest_<ContainerAllocator> Type;

  SetIORequest_()
    : fun(0)
    , pin(0)
    , state(0.0)  {
    }
  SetIORequest_(const ContainerAllocator& _alloc)
    : fun(0)
    , pin(0)
    , state(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _fun_type;
  _fun_type fun;

   typedef int8_t _pin_type;
  _pin_type pin;

   typedef float _state_type;
  _state_type state;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FUN_SET_RobotBoardUserDO)
  #undef FUN_SET_RobotBoardUserDO
#endif
#if defined(_WIN32) && defined(FUN_SET_RobotBoardUserAO)
  #undef FUN_SET_RobotBoardUserAO
#endif
#if defined(_WIN32) && defined(FUN_SET_ToolDigitalIO)
  #undef FUN_SET_ToolDigitalIO
#endif
#if defined(_WIN32) && defined(FUN_SET_RobotToolAO)
  #undef FUN_SET_RobotToolAO
#endif
#if defined(_WIN32) && defined(FUN_SET_ToolPowerType)
  #undef FUN_SET_ToolPowerType
#endif

  enum {
    FUN_SET_RobotBoardUserDO = 1,
    FUN_SET_RobotBoardUserAO = 2,
    FUN_SET_ToolDigitalIO = 3,
    FUN_SET_RobotToolAO = 4,
    FUN_SET_ToolPowerType = 5,
  };


  typedef boost::shared_ptr< ::aubo_msgs::SetIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aubo_msgs::SetIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetIORequest_

typedef ::aubo_msgs::SetIORequest_<std::allocator<void> > SetIORequest;

typedef boost::shared_ptr< ::aubo_msgs::SetIORequest > SetIORequestPtr;
typedef boost::shared_ptr< ::aubo_msgs::SetIORequest const> SetIORequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aubo_msgs::SetIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aubo_msgs::SetIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aubo_msgs::SetIORequest_<ContainerAllocator1> & lhs, const ::aubo_msgs::SetIORequest_<ContainerAllocator2> & rhs)
{
  return lhs.fun == rhs.fun &&
    lhs.pin == rhs.pin &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aubo_msgs::SetIORequest_<ContainerAllocator1> & lhs, const ::aubo_msgs::SetIORequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aubo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::aubo_msgs::SetIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aubo_msgs::SetIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aubo_msgs::SetIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aubo_msgs::SetIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aubo_msgs::SetIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aubo_msgs::SetIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aubo_msgs::SetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90bfa84517e13b8c5bee48efbf6df45f";
  }

  static const char* value(const ::aubo_msgs::SetIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90bfa84517e13b8cULL;
  static const uint64_t static_value2 = 0x5bee48efbf6df45fULL;
};

template<class ContainerAllocator>
struct DataType< ::aubo_msgs::SetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aubo_msgs/SetIORequest";
  }

  static const char* value(const ::aubo_msgs::SetIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aubo_msgs::SetIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 FUN_SET_RobotBoardUserDO = 1\n"
"int8 FUN_SET_RobotBoardUserAO = 2\n"
"int8 FUN_SET_ToolDigitalIO = 3\n"
"int8 FUN_SET_RobotToolAO = 4\n"
"int8 FUN_SET_ToolPowerType = 5\n"
"int8 fun\n"
"int8 pin\n"
"float32 state\n"
;
  }

  static const char* value(const ::aubo_msgs::SetIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aubo_msgs::SetIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fun);
      stream.next(m.pin);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aubo_msgs::SetIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aubo_msgs::SetIORequest_<ContainerAllocator>& v)
  {
    s << indent << "fun: ";
    Printer<int8_t>::stream(s, indent + "  ", v.fun);
    s << indent << "pin: ";
    Printer<int8_t>::stream(s, indent + "  ", v.pin);
    s << indent << "state: ";
    Printer<float>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUBO_MSGS_MESSAGE_SETIOREQUEST_H
