// Generated by gencpp from file aubo_msgs/SetPayload.msg
// DO NOT EDIT!


#ifndef AUBO_MSGS_MESSAGE_SETPAYLOAD_H
#define AUBO_MSGS_MESSAGE_SETPAYLOAD_H

#include <ros/service_traits.h>


#include <aubo_msgs/SetPayloadRequest.h>
#include <aubo_msgs/SetPayloadResponse.h>


namespace aubo_msgs
{

struct SetPayload
{

typedef SetPayloadRequest Request;
typedef SetPayloadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPayload
} // namespace aubo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aubo_msgs::SetPayload > {
  static const char* value()
  {
    return "7f12eb632882cb73e5721178d0073e39";
  }

  static const char* value(const ::aubo_msgs::SetPayload&) { return value(); }
};

template<>
struct DataType< ::aubo_msgs::SetPayload > {
  static const char* value()
  {
    return "aubo_msgs/SetPayload";
  }

  static const char* value(const ::aubo_msgs::SetPayload&) { return value(); }
};


// service_traits::MD5Sum< ::aubo_msgs::SetPayloadRequest> should match
// service_traits::MD5Sum< ::aubo_msgs::SetPayload >
template<>
struct MD5Sum< ::aubo_msgs::SetPayloadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aubo_msgs::SetPayload >::value();
  }
  static const char* value(const ::aubo_msgs::SetPayloadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aubo_msgs::SetPayloadRequest> should match
// service_traits::DataType< ::aubo_msgs::SetPayload >
template<>
struct DataType< ::aubo_msgs::SetPayloadRequest>
{
  static const char* value()
  {
    return DataType< ::aubo_msgs::SetPayload >::value();
  }
  static const char* value(const ::aubo_msgs::SetPayloadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aubo_msgs::SetPayloadResponse> should match
// service_traits::MD5Sum< ::aubo_msgs::SetPayload >
template<>
struct MD5Sum< ::aubo_msgs::SetPayloadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aubo_msgs::SetPayload >::value();
  }
  static const char* value(const ::aubo_msgs::SetPayloadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aubo_msgs::SetPayloadResponse> should match
// service_traits::DataType< ::aubo_msgs::SetPayload >
template<>
struct DataType< ::aubo_msgs::SetPayloadResponse>
{
  static const char* value()
  {
    return DataType< ::aubo_msgs::SetPayload >::value();
  }
  static const char* value(const ::aubo_msgs::SetPayloadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUBO_MSGS_MESSAGE_SETPAYLOAD_H
