(cl:defpackage aubo_msgs-srv
  (:use )
  (:export
   "GETFK"
   "<GETFK-REQUEST>"
   "GETFK-REQUEST"
   "<GETFK-RESPONSE>"
   "GETFK-RESPONSE"
   "GETIK"
   "<GETIK-REQUEST>"
   "GETIK-REQUEST"
   "<GETIK-RESPONSE>"
   "GETIK-RESPONSE"
   "SETIO"
   "<SETIO-REQUEST>"
   "SETIO-REQUEST"
   "<SETIO-RESPONSE>"
   "SETIO-RESPONSE"
   "SETPAYLOAD"
   "<SETPAYLOAD-REQUEST>"
   "SETPAYLOAD-REQUEST"
   "<SETPAYLOAD-RESPONSE>"
   "SETPAYLOAD-RESPONSE"
  ))

